    server {
        listen 443 ssl;
        server_name smartaf.ru;
        ssl_certificate /etc/letsencrypt/live/smartaf.ru/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/smartaf.ru/privkey.pem;

        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
            try_files $uri $uri/ /index.html;
        }
    }
    server {
        listen 443 ssl;
        server_name api.smartaf.ru; # Этот блок слушает ТОЛЬКО поддомен

        ssl_certificate /etc/letsencrypt/live/smartaf.ru/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/smartaf.ru/privkey.pem;

        # Теперь корень поддомена (/) сразу ведет в FastAPI
        location / {
            proxy_pass http://azs_fastapi_backend:8000; # Без слэша на конце, так как префикс отрезать не нужно

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
