    server {
        listen 443 ssl;
        server_name api.smartaf.ru smartaf.ru;
        ssl_certificate /etc/letsencrypt/live/smartaf.ru/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/smartaf.ru/privkey.pem;

        location /api/ {
        # Слэш в конце '8000/' ОБЯЗАТЕЛЕН — он отрезает слово '/api' перед отправкой в FastAPI
            proxy_pass http://azs_fastapi_backend:8000/;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
         proxy_set_header X-Forwarded-Proto $scheme;
        }
        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;

            # Это критически важно для React: если пользователь обновит страницу
            # внутри приложения (например, /profile), Nginx не выдаст 404, а перенаправит на index.html
            try_files $uri $uri/ /index.html;
        }
    }
